### ISSUE TITLE
Hello, I upgraded chatgpt to the plus version, and the program has the following error. This error also occurs when I try not to use the plus version, how should I deal with this problem.

### ISSUE THREAD

**Issue by lean-wang** [PawanOsman/PyGPT#12]
Connected to server
Token expired, getting new token
Getting tokens...
Ready!!
Error: An error ocurred. Try refreshing your browser.
packet queue is empty, aborting
Traceback (most recent call last):
  File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 13, in <module>
    asyncio.run(main())
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 8, in main
    answer = await chat_gpt.ask('What is the capital of France?')
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py", line 149, in ask
    conversation['conversation_id'] = data['conversationId']
KeyError: 'conversationId'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py", line 69, in save_interval
    self.save()
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py", line 45, in save
    conversation['last_active'] = conversation['last_active'].isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e0689d0>

**Comment by yakun0622** [comment]
![image](https://user-images.githubusercontent.com/11678144/218421355-d2b2fba1-9bb8-4f78-bbf2-023af13c5034.png)

**Comment by lean-wang** [comment]
Thank you for your reply. I think this version of the program is not suitable for chatgpt plus. It will still report that it is not the plus version and can run normally.

**Comment by lean-wang** [comment]
Thank you for your reply. I think this version of the program does not match chatgpt plus. The plus version will report this error,
---------------------------------
Connected to server
Token expired, getting new token
Getting tokens...
Error getting session: Authentication failed.  Please ensure that your SessionToken is valid.  If you have 5 failed authentications, your IP will be suspended for one minute.  you have 4 failed authentications.
Token expired, getting new token。
---------------------------------
Those that are not running the plus version can run normally.

**Comment by XueMeijing** [comment]
> ![image](https://user-images.githubusercontent.com/11678144/218421355-d2b2fba1-9bb8-4f78-bbf2-023af13c5034.png)

nice, it works well, thank you

**Comment by PawanOsman** [comment]
you need to set `pro_account` to `True`

```python
chat_gpt = PyGPT('eyJhbGciOiJkaXIiLCJlbmMiOiJBMR0NN....', pro_account=True)
```
