### ISSUE TITLE
socketio.exceptions.TimeoutError Frequently

### ISSUE THREAD

**Issue by Ulysses0817** [PawanOsman/PyGPT#2]
Hi PawanOsman,
Thanks for your great api!
Here I have a problem. I'm always getting `socketio.exceptions.TimeoutError` while asking for a long answer.
Foer example, when I send prompts like following text, which means that I want chatgpt to generate 5 nonprofit qustions about children's charity. 
```
生成5道公益问题，问题主要针对儿童的健康保护，希望和关注自闭症儿童或者关注儿童教育相关。同时需要满足以下条件:
1）题目具有公益性
2）有2至4个选项
3）题目最多24个字
4）选项最多11个字
5）只有一个正确选项
6）包含解析，解析最多126个字
```
I will get socketio.exceptions.TimeoutError when I request with above text. However, if I change the `5 nonprofit qustions` to `1 nonprofit qustions`, the api is more likely to give me a response. Could you help me with this?
Besides, the error is like:
```
packet queue is empty, aborting
2023-01-06 14:52:02,188 - engineio.client - ERROR - packet queue is empty, aborting
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 33162)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/root/miniconda3/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/miniconda3/lib/python3.9/site-packages/wechatrobot/WeChatRobot.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/root/miniconda3/lib/python3.9/site-packages/wechatrobot/WeChatRobot.py", line 105, in handle
    self.receive_callback(msg)
  File "/root/miniconda3/lib/python3.9/site-packages/wechatrobot/WeChatRobot.py", line 89, in receive_callback
    Bus.emit("group_msg", msg)
  File "/root/miniconda3/lib/python3.9/site-packages/wechatrobot/Bus.py", line 14, in emit
    results.append(f(*args, **kwargs))
  File "/usr/games/wechat_gpt/wxbot_v2.py", line 340, in on_group_msg
    call_back(message, sender, wxid, exclude_groups=groups)
  File "/usr/games/wechat_gpt/wxbot_v2.py", line 273, in call_back
    reply = asyncio.run(poapi(PyGPT(current_bot["session_id"]), query_data, bot, sender, db))
  File "/root/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/games/wechat_gpt/chatgpt/poChatgpt_async.py", line 12, in poapi
    reply = await chat_gpt.ask(query_data)
  File "/usr/games/wechat_gpt/chatgpt/poChatgpt_async.py", line 77, in ask
    data = await self.socket.call('askQuestion', ask_data)
  File "/root/miniconda3/lib/python3.9/site-packages/socketio/asyncio_client.py", line 297, in call
    raise exceptions.TimeoutError() from None
socketio.exceptions.TimeoutError
```

Regards,
Ulysses

**Comment by Ulysses0817** [comment]
I'd like to make an addition, when I send some text using undetected chromedriver, chatgpt'll reply to me normally with truncated answers.

**Comment by Ulysses0817** [comment]
solved! `socketio.AsyncClient.call()` has a argument `timeout`, the default value is 60. If the timeout is reached before the client acknowledges the event, then a TimeoutError exception is raised.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/29434950/211127688-e86a09b8-0573-4825-ba16-89df8b56010f.png">

**Comment by PawanOsman** [comment]
Thank you for solving this issue. I updated the package based on your solution.

**Comment by celunah** [comment]
> Thank you for solving this issue. I updated the package based on your solution.

I am still getting the TimeoutError, please fix the lib

**Comment by PawanOsman** [comment]
> > Thank you for solving this issue. I updated the package based on your solution.
> 
> I am still getting the TimeoutError, please fix the lib

please explain your issue and provide a reproducible example

**Comment by celunah** [comment]
> > > Thank you for solving this issue. I updated the package based on your solution.
> > 
> > 
> > I am still getting the TimeoutError, please fix the lib
> 
> please explain your issue and provide a reproducible example

I just used the example code from this repo and placed my session token, it said "Connected" and "Ready" but ultimately waited for around a minute then I got the TimeoutError. I don't know what's wrong.

**Comment by PawanOsman** [comment]
> I just used the example code from this repo and placed my session token, it said "Connected" and "Ready" but ultimately waited for around a minute then I got the TimeoutError. I don't know what's wrong.

The default timeout is 2 minutes. If your request takes longer to get a response from ChatGPT, you will need to set a higher timeout value. You can do this by setting the `timeout` to a higher number, for example `240`.

```python
chat_gpt = PyGPT('eyJhbGciOiJkaXIiLCJlbmMiOiJBMR0NN....', timeout=240)
```
