### ISSUE TITLE
client_session: <aiohttp.client.ClientSession object at 0x7f56a8351450>

### ISSUE THREAD

**Issue by SeolhwaLee** [PawanOsman/PyGPT#4]
It was fine when I tried your example for the first time. 
But I got this error when I run the code second time. 
```Starting. Please wait...
Connected to server
Ready!!
packet queue is empty, aborting
Traceback (most recent call last):
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 113, in <module>
    main()
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 107, in main
    asyncio.run(async_main(args))
  File "/home/seolhwa/miniconda3/envs/chatgpt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/seolhwa/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 26, in async_main
    answer = await chat_gpt.ask(q[0])
  File "/home/seolhwa/PycharmProjects/respective/pygpt.py", line 95, in ask
    conversation['conversation_id'] = data['conversationId']
KeyError: 'conversationId'
```

**Comment by PawanOsman** [comment]
Make sure your session token is not expired

**Comment by SeolhwaLee** [comment]
I used the updated session token and it has the same error after giving 22 queries in less than 2 min.
Do you think it has a relation with timeout? I changed offset time to 200 minutes `offset = datetime.timedelta(minutes=200)` but still show the same problem. Or do you think it has any query limit?

```
packet queue is empty, aborting
Traceback (most recent call last):
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 114, in <module>
    main()
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 108, in main
    asyncio.run(async_main(args))
  File "/home/seolhwa/miniconda3/envs/chatgpt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/seolhwa/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/seolhwa/PycharmProjects/respective/chatgpt_conv.py", line 27, in async_main
    answer = await chat_gpt.ask(q[0])
  File "/home/seolhwa/PycharmProjects/respective/pygpt.py", line 95, in ask
    conversation['conversation_id'] = data['conversationId']
KeyError: 'conversationId'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb47accd450>
```

**Comment by PawanOsman** [comment]
22 queries within a 2-minute period is a high volume and your account may be rate limited by OpenAI.
