### ISSUE TITLE
Hello, I can access chatgpt normally, and the session is only obtained. Why would you run your program and report the following error.

### ISSUE THREAD

**Issue by lean-wang** [PawanOsman/PyGPT#7]
Hello, I can access chatgpt normally, and the session is only obtained. Why would you run your program and report the following error.
```
Connected to server
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<PyGPT.check_tokens() done, defined at /Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py:39> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py", line 48, in check_tokens
    await self.get_tokens()
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pygpt.py", line 109, in get_tokens
    data = await self.socket.call(event='getSession', data=self.session_token, timeout=self.timeout)
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/socketio/asyncio_client.py", line 297, in call
    raise exceptions.TimeoutError() from None
socketio.exceptions.TimeoutError
```

**Comment by PawanOsman** [comment]
Hey, sorry for the recent downtime that was caused by a limitation or issue from OpenAI.
we already fixed it now all 13 bypass servers are working
